export const customerData = [
  {
    kode_pelanggan: "PLG001",
    nama_pelanggan: "Andi Wijaya",
    alamat_pelanggan: "Jl. Kenanga No. 3, Jakarta",
    telp_pelanggan: "0812-3456-7890",
    email_pelanggan: "andi.wijaya@gmail.com",
  },
  {
    kode_pelanggan: "PLG002",
    nama_pelanggan: "Siti Nurhaliza",
    alamat_pelanggan: "Jl. Melati No. 12, Bandung",
    telp_pelanggan: "0821-9876-5432",
    email_pelanggan: "siti.nurhaliza@yahoo.com",
  },
  {
    kode_pelanggan: "PLG003",
    nama_pelanggan: "Budi Santoso",
    alamat_pelanggan: "Jl. Mawar No. 7, Surabaya",
    telp_pelanggan: "0852-3344-5566",
    email_pelanggan: "budi.santoso@gmail.com",
  },
  {
    kode_pelanggan: "PLG004",
    nama_pelanggan: "Rina Amelia",
    alamat_pelanggan: "Jl. Anggrek No. 21, Semarang",
    telp_pelanggan: "0878-2211-3344",
    email_pelanggan: "rina.amelia@mail.com",
  },
  {
    kode_pelanggan: "PLG005",
    nama_pelanggan: "Dedi Supriadi",
    alamat_pelanggan: "Jl. Merpati No. 5, Bogor",
    telp_pelanggan: "0813-7777-8888",
    email_pelanggan: "dedi.s@gmail.com",
  },
  {
    kode_pelanggan: "PLG006",
    nama_pelanggan: "Lina Marlina",
    alamat_pelanggan: "Jl. Rajawali No. 10, Bekasi",
    telp_pelanggan: "0822-9999-0000",
    email_pelanggan: "lina.marlina@hotmail.com",
  },
  {
    kode_pelanggan: "PLG007",
    nama_pelanggan: "Agus Prasetyo",
    alamat_pelanggan: "Jl. Cendana No. 18, Yogyakarta",
    telp_pelanggan: "0851-2345-6789",
    email_pelanggan: "agus.p@gmail.com",
  },
  {
    kode_pelanggan: "PLG008",
    nama_pelanggan: "Diana Kartika",
    alamat_pelanggan: "Jl. Sakura No. 2, Malang",
    telp_pelanggan: "0896-5432-1234",
    email_pelanggan: "diana.kartika@outlook.com",
  },
  {
    kode_pelanggan: "PLG009",
    nama_pelanggan: "Rudi Hartono",
    alamat_pelanggan: "Jl. Teratai No. 9, Medan",
    telp_pelanggan: "0838-1111-2222",
    email_pelanggan: "rudi.hartono@gmail.com",
  },
  {
    kode_pelanggan: "PLG010",
    nama_pelanggan: "Nina Suryani",
    alamat_pelanggan: "Jl. Flamboyan No. 15, Palembang",
    telp_pelanggan: "0819-8765-4321",
    email_pelanggan: "nina.suryani@mail.com",
  },
];
