export const laporanMutasiMasuk = [
  {
    no: 1,
    tanggal_transaksi: "2025-06-01",
    nama_produk: "Kertas A4 80gsm",
    kode_supplier: "SUP001",
    kuantitas: 100,
    keterangan: "Restock rutin",
  },
  {
    no: 2,
    tanggal_transaksi: "2025-06-02",
    nama_produk: "Tinta Printer Canon",
    kode_supplier: "SUP002",
    kuantitas: 25,
    keterangan: "Penggantian tinta habis",
  },
  {
    no: 3,
    tanggal_transaksi: "2025-06-03",
    nama_produk: "Mouse Wireless Logitech",
    kode_supplier: "SUP003",
    kuantitas: 10,
    keterangan: "Permintaan unit baru",
  },
  {
    no: 4,
    tanggal_transaksi: "2025-06-04",
    nama_produk: "Monitor 24 inch IPS",
    kode_supplier: "SUP004",
    kuantitas: 5,
    keterangan: "Penambahan unit kantor",
  },
  {
    no: 5,
    tanggal_transaksi: "2025-06-05",
    nama_produk: "Kabel LAN 10m",
    kode_supplier: "SUP001",
    kuantitas: 20,
    keterangan: "Kebutuhan instalasi jaringan",
  },
  {
    no: 6,
    tanggal_transaksi: "2025-06-06",
    nama_produk: "Meja Kerja Kayu",
    kode_supplier: "SUP005",
    kuantitas: 3,
    keterangan: "Mutasi antar gudang",
  },
  {
    no: 7,
    tanggal_transaksi: "2025-06-07",
    nama_produk: "Stabilo Warna",
    kode_supplier: "SUP002",
    kuantitas: 50,
    keterangan: "Restock perlengkapan kantor",
  },
  {
    no: 8,
    tanggal_transaksi: "2025-06-08",
    nama_produk: "Laptop Lenovo i5",
    kode_supplier: "SUP006",
    kuantitas: 2,
    keterangan: "Pengadaan perangkat baru",
  },
  {
    no: 9,
    tanggal_transaksi: "2025-06-09",
    nama_produk: "Harddisk External 1TB",
    kode_supplier: "SUP004",
    kuantitas: 4,
    keterangan: "Backup data divisi",
  },
  {
    no: 10,
    tanggal_transaksi: "2025-06-10",
    nama_produk: "Flashdisk 32GB",
    kode_supplier: "SUP003",
    kuantitas: 40,
    keterangan: "Distribusi ke departemen",
  },
];
