export const productsData = [
  {
    product_code: "P001",
    barcode: "1234567890123",
    product_name: "Apple Juice",
    category: "Beverage",
    supplier_name: "Fresh Farm Ltd",
    packing: "12 x 1L",
    quantity: 120,
    warehouse_name: "Warehouse A",
  },
  {
    product_code: "P002",
    barcode: "2234567890123",
    product_name: "Orange Soda",
    category: "Beverage",
    supplier_name: "Spark Drinks",
    packing: "24 x 330ml",
    quantity: 85,
    warehouse_name: "Warehouse B",
  },
  {
    product_code: "P003",
    barcode: "3234567890123",
    product_name: "Organic Honey",
    category: "Food",
    supplier_name: "Sweet Nature",
    packing: "6 x 500g",
    quantity: 45,
    warehouse_name: "Warehouse A",
  },
  {
    product_code: "P004",
    barcode: "4234567890123",
    product_name: "Whole Wheat Bread",
    category: "Bakery",
    supplier_name: "Daily Bread Co",
    packing: "20 pcs",
    quantity: 30,
    warehouse_name: "Warehouse C",
  },
  {
    product_code: "P005",
    barcode: "5234567890123",
    product_name: "Cheddar Cheese",
    category: "Dairy",
    supplier_name: "Golden Cows",
    packing: "10 x 200g",
    quantity: 60,
    warehouse_name: "Warehouse B",
  },
  {
    product_code: "P006",
    barcode: "6234567890123",
    product_name: "Tomato Ketchup",
    category: "Condiment",
    supplier_name: "Red Sauce Co",
    packing: "12 x 500ml",
    quantity: 100,
    warehouse_name: "Warehouse A",
  },
  {
    product_code: "P007",
    barcode: "7234567890123",
    product_name: "Salted Butter",
    category: "Dairy",
    supplier_name: "Butter World",
    packing: "12 x 250g",
    quantity: 40,
    warehouse_name: "Warehouse B",
  },
  {
    product_code: "P008",
    barcode: "8234567890123",
    product_name: "Spaghetti Pasta",
    category: "Food",
    supplier_name: "Italiano Supplies",
    packing: "20 x 500g",
    quantity: 75,
    warehouse_name: "Warehouse C",
  },
  {
    product_code: "P009",
    barcode: "9234567890123",
    product_name: "Green Tea",
    category: "Beverage",
    supplier_name: "Zen Tea Ltd",
    packing: "30 x 100g",
    quantity: 55,
    warehouse_name: "Warehouse A",
  },
  {
    product_code: "P010",
    barcode: "0234567890123",
    product_name: "Almond Milk",
    category: "Beverage",
    supplier_name: "Healthy Choice",
    packing: "12 x 1L",
    quantity: 90,
    warehouse_name: "Warehouse B",
  },
];
