export const returPenjualanData = [
  {
    no_invoice: "INV-001",
    warehouse: "Gudang Jakarta",
    no_document: "RET-001",
    product_code: "P001",
    barcode: "8991000000011",
    product_name: "Sabun Mandi Lux 100gr",
    category: "Toiletries",
    supplier_name: "PT. Sumber Jaya",
    packing: "Box x 12",
    transaction_date: "2025-04-20",
    admin_name: "Andi Wijaya",
    invoice_status: "Approved",
    invoice_type: "Cash",
  },
  {
    no_invoice: "INV-002",
    warehouse: "Gudang Surabaya",
    no_document: "RET-002",
    product_code: "P002",
    barcode: "8991000000022",
    product_name: "Shampoo Clear 200ml",
    category: "Hair Care",
    supplier_name: "CV. Mitra Abadi",
    packing: "Dus x 24",
    transaction_date: "2025-04-21",
    admin_name: "Siti Nurhaliza",
    invoice_status: "Pending",
    invoice_type: "Credit",
  },
  {
    no_invoice: "INV-003",
    warehouse: "Gudang Bandung",
    no_document: "RET-003",
    product_code: "P003",
    barcode: "8991000000033",
    product_name: "Pasta Gigi Pepsodent 75gr",
    category: "Oral Care",
    supplier_name: "PT. Indo Makmur",
    packing: "Pack x 10",
    transaction_date: "2025-04-22",
    admin_name: "Budi Santoso",
    invoice_status: "Approved",
    invoice_type: "Transfer",
  },
  {
    no_invoice: "INV-004",
    warehouse: "Gudang Medan",
    no_document: "RET-004",
    product_code: "P004",
    barcode: "8991000000044",
    product_name: "Tissue Paseo 250s",
    category: "Household",
    supplier_name: "PT. Global Sentosa",
    packing: "Carton x 6",
    transaction_date: "2025-04-22",
    admin_name: "Rina Amelia",
    invoice_status: "Rejected",
    invoice_type: "Cash",
  },
  {
    no_invoice: "INV-005",
    warehouse: "Gudang Semarang",
    no_document: "RET-005",
    product_code: "P005",
    barcode: "8991000000055",
    product_name: "Minyak Goreng Bimoli 1L",
    category: "Groceries",
    supplier_name: "CV. Bintang Timur",
    packing: "Jerigen x 6",
    transaction_date: "2025-04-23",
    admin_name: "Dedi Supriadi",
    invoice_status: "Approved",
    invoice_type: "Credit",
  },
  {
    no_invoice: "INV-006",
    warehouse: "Gudang Yogyakarta",
    no_document: "RET-006",
    product_code: "P006",
    barcode: "8991000000066",
    product_name: "Susu UHT Indomilk 1L",
    category: "Dairy",
    supplier_name: "PT. Cahaya Baru",
    packing: "Dus x 12",
    transaction_date: "2025-04-23",
    admin_name: "Lina Marlina",
    invoice_status: "Pending",
    invoice_type: "Cash",
  },
  {
    no_invoice: "INV-007",
    warehouse: "Gudang Bekasi",
    no_document: "RET-007",
    product_code: "P007",
    barcode: "8991000000077",
    product_name: "Air Mineral Aqua 600ml",
    category: "Beverages",
    supplier_name: "CV. Sinar Mas",
    packing: "Paket x 24",
    transaction_date: "2025-04-24",
    admin_name: "Agus Prasetyo",
    invoice_status: "Approved",
    invoice_type: "Transfer",
  },
  {
    no_invoice: "INV-008",
    warehouse: "Gudang Malang",
    no_document: "RET-008",
    product_code: "P008",
    barcode: "8991000000088",
    product_name: "Kopi Kapal Api 65gr",
    category: "Beverages",
    supplier_name: "PT. Nusantara Raya",
    packing: "Pack x 10",
    transaction_date: "2025-04-24",
    admin_name: "Diana Kartika",
    invoice_status: "Rejected",
    invoice_type: "Cash",
  },
  {
    no_invoice: "INV-009",
    warehouse: "Gudang Bogor",
    no_document: "RET-009",
    product_code: "P009",
    barcode: "8991000000099",
    product_name: "Kecap ABC 135ml",
    category: "Condiments",
    supplier_name: "CV. Mega Utama",
    packing: "Box x 24",
    transaction_date: "2025-04-25",
    admin_name: "Rudi Hartono",
    invoice_status: "Approved",
    invoice_type: "Credit",
  },
  {
    no_invoice: "INV-010",
    warehouse: "Gudang Palembang",
    no_document: "RET-010",
    product_code: "P010",
    barcode: "8991000000100",
    product_name: "Mi Instan Indomie Goreng",
    category: "Groceries",
    supplier_name: "PT. Anugerah Sejahtera",
    packing: "Dus x 40",
    transaction_date: "2025-04-25",
    admin_name: "Nina Suryani",
    invoice_status: "Pending",
    invoice_type: "Transfer",
  },
];
