export const suppliersData = [
  {
    kode_principal: "PR001",
    nama_principal: "PT. Sumber Jaya",
    alamat_principal: "Jl. Merdeka No. 10, Jakarta",
    telp_principal: "021-1234567",
    email_principal: "info@sumberjaya.co.id",
  },
  {
    kode_principal: "PR002",
    nama_principal: "CV. Mitra Abadi",
    alamat_principal: "Jl. Sudirman No. 55, Bandung",
    telp_principal: "022-7654321",
    email_principal: "sales@mitraabadi.co.id",
  },
  {
    kode_principal: "PR003",
    nama_principal: "PT. Indo Makmur",
    alamat_principal: "Jl. Diponegoro No. 23, Surabaya",
    telp_principal: "031-5678901",
    email_principal: "support@indomakmur.com",
  },
  {
    kode_principal: "PR004",
    nama_principal: "PT. Global Sentosa",
    alamat_principal: "Jl. Gatot Subroto No. 88, Medan",
    telp_principal: "061-3344556",
    email_principal: "contact@globalsentosa.com",
  },
  {
    kode_principal: "PR005",
    nama_principal: "CV. Bintang Timur",
    alamat_principal: "Jl. Ahmad Yani No. 12, Semarang",
    telp_principal: "024-2233445",
    email_principal: "marketing@bintangtimur.co.id",
  },
  {
    kode_principal: "PR006",
    nama_principal: "PT. Cahaya Baru",
    alamat_principal: "Jl. Malioboro No. 77, Yogyakarta",
    telp_principal: "0274-5566778",
    email_principal: "admin@cahayabaru.co.id",
  },
  {
    kode_principal: "PR007",
    nama_principal: "CV. Sinar Mas",
    alamat_principal: "Jl. Pemuda No. 5, Malang",
    telp_principal: "0341-889900",
    email_principal: "info@sinarmas.co.id",
  },
  {
    kode_principal: "PR008",
    nama_principal: "PT. Nusantara Raya",
    alamat_principal: "Jl. Ahmad Yani No. 45, Balikpapan",
    telp_principal: "0542-3344556",
    email_principal: "hello@nusantararaya.com",
  },
  {
    kode_principal: "PR009",
    nama_principal: "CV. Mega Utama",
    alamat_principal: "Jl. Imam Bonjol No. 19, Bogor",
    telp_principal: "0251-6677889",
    email_principal: "mega@megautama.co.id",
  },
  {
    kode_principal: "PR010",
    nama_principal: "PT. Anugerah Sejahtera",
    alamat_principal: "Jl. Soekarno Hatta No. 101, Palembang",
    telp_principal: "0711-1122334",
    email_principal: "info@anugerahsejahtera.co.id",
  },
];
